src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    // Pour utiliser les Traits de Gedmo,
    // vous devrez faire un 'composer require gedmo/doctrine-extensions'.
    /*
     Ces deux 'use' sont des "traits", cela permet de faire comme un 'include'
     mais pour une Class.
     Ces instructions ajoutent 3 propriétés à la class Article :
       - $createdAt
       - $updatedAt
       - $deletedAt

    Mais aussi les getters/setters appropriés.
     */
    use TimestampableEntity;
    use SoftDeleteableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $alias = null;

    #[ORM\Column(length: 255)]
    private ?string $subtitle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Commentary::class)]
    private Collection $commentaries;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries->add($commentary);
            $commentary->setArticle($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getArticle() === $this) {
                $commentary->setArticle(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;
    use SoftDeleteableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $firstname = null;

    #[ORM\Column(length: 50)]
    private ?string $lastname = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Article::class)]
    private Collection $articles;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Commentary::class)]
    private Collection $commentaries;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->commentaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getFullname(): string
    {
        return $this->getFirstname() . ' ' . $this->getLastname();
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries->add($commentary);
            $commentary->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getAuthor() === $this) {
                $commentary->setAuthor(null);
            }
        }

        return $this;
    }



}// end class

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Category;
use App\Repository\ArticleRepository;
use App\Repository\CommentaryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    #[Route('/voir-articles/{alias}', name: 'show_articles_from_category', methods: ['GET'])]
    public function showArticlesFromCategory(Category $category, ArticleRepository $repository): Response
    {
        $articles = $repository->findBy([
            'deletedAt' => null,
            'category' => $category->getId()
        ]);

        return $this->render('article/show_articles_from_categories.html.twig', [
            'articles' => $articles,
            'category' => $category
        ]);
    }

    #[Route('{cat_alias}/{art_alias}_{id}', name: 'show_article', methods: ['GET'])]
    public function showArticle(Article $article, CommentaryRepository $commentaryRepository): Response
    {
        $commentaries = $commentaryRepository->findBy(['deletedAt' => null, 'article' => $article->getId()]);

        return $this->render('article/show_article.html.twig', [
            'article' => $article,
            'commentaries' => $commentaries
        ]);
    }
}

templates/article/show_article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}


{% block body %}

    <div class="row">
        <div class="col-10 mx-auto my-4">
            {% include 'include/_flashes.html.twig' %}
        </div>
    </div>

    <div class="row">
        <div class="col-10 mx-auto mb-4">

            <div class="card">
                <div class="card-header">
                    <h1 class="text-center card-title mb-5">{{ article.title }}</h1>
                    <h4 class="text-center text-secondary mb-3">{{ article.subtitle }}</h4>
                </div>
                <ul class="list-group list-group flush">
                    <li class="list-group-item text-center text-muted">Crée {{ article.createdAt | ago(locale='fr') }} | Par <u class="text-underline">{{ article.author.fullname }}</u></li>
                </ul>
                <img src="{{ asset('uploads/' ~ article.photo) }}" alt="{{ article.title }}" class="img-custom2">
                <div class="card-body">
                    <p class="card-text col-8 mx-auto my-4 text-center">{{ article.content | raw }}</p>
                </div>
            </div>

        </div>
    </div>

    {{ render(url('add_commentary', {'id': article.id})) }}

    <div class="row">
        <div class="col-6 mx-auto">

            <h3 class="mb-5">Espace Commentaires :</h3>

            {% for commentary in commentaries | reverse %}

                <div class="alert alert-dark mb-3" role="alert">
                    <h4 class="alert-heading">{{ commentary.author.fullname }} <span class="h6">posté {{ commentary.createdAt | ago(locale='fr') }}</span></h4>
                    <p>{{ commentary.comment }}</p>
                    <hr>
                    <p class="mb-0">Partager :
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                        <a href="#"><i class="fa-brands fa-twitter"></i></a>
                        <a href="#"><i class="fa-brands fa-facebook"></i></a>

                        {% if app.user is same as commentary.author %}
                            <a href="{{ path('soft_delete_commentary', {'id': commentary.id}) }}?article_id={{ article.id }}" class="float-right"><i class="fa-solid fa-trash"></i></a>
                        {% endif %}
                    </p>
                </div>

            {% else %}

            <div class="alert alert-warning mb-3" role="alert">
                <p class="text-center fw-bolder">Aucun commentaire pour cet article</p>
            </div>

            {% endfor %}

        </div>
    </div>

{% endblock %}

templates/article/show_articles_from_categories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégorie {{ category.name }}{% endblock %}

{% block body %}

    <h1 class="text-center my-3">Catégorie {{ category.name }}</h1>

    <div class="row">
        <div class="col-10 mx-auto my-5">

            {% for article in articles | reverse %}

                <div class="row mb-4 border-top p-3">
                    <a href="{{ path('show_article', {'cat_alias': article.category.alias, 'art_alias': article.alias, 'id': article.id}) }}" title="Voir l'article" class="d-flex text-decoration-none">

                        <div class="col-5">
                            <img src="{{ asset('uploads/' ~ article.photo) }}" alt="{{ article.title }}" class="img-custom rounded">
                        </div>

                        <div class="col-7 ms-4">
                            <h2 class="text-dark align-middle">{{ article.title }}</h2>
                            <p class="text-muted align-middle">{{ article.subtitle }}</p>
                        </div>

                    </a>
                </div>

            {% else %}
                <h3 class="text-center text-warning mt-2">Aucun article pour cette catégorie !</h3>
            {% endfor %}

        </div>
    </div>

{% endblock %}